#i have fetched the data from opentrivia.com
question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The first computer bug was formed by faulty wires.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "&quot;Windows NT&quot; is a monolithic kernel.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "AMD created the first consumer 64-bit processor.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Android versions are named in alphabetical order.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                                      "correct_answer": "False", "incorrect_answers": ["True"]}
]
